name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v4
      - name: asdf_plugin_add
        run: |
          echo "$ASDF_DIR/bin" >> "$GITHUB_PATH"
          set -x
          asdf plugin add wsshuttle .
          asdf list all wsshuttle
          asdf install wsshuttle latest
          asdf set wsshuttle latest

          wsshuttle --version
